### PR TITLE
Added Support for Virtual Machine (Windows Server)

### PR DESCRIPTION
**Pull request by AbhiOnGithub**

### CODE REVIEW

**Comment by abhiongithub** [comment]
@jasallen @cmatskas @jasallen can someone of you please review this PR.
Thanks

**Comment by cmatskas** [comment]
I’ve reviewed it and I’ll merge later today or tomorrow.
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pulimento** [comment]
Hello Abishek,

First of all, thanks to contribute to this repo. I've rejected this PR because I consider it too big, and changing many parts at once. Viewing the code online, the part that adds support to virtual machines looks good!

Please, divide this PR in two PRs, one for the virtual machine support, and another for the NuGet updates. I think it's better that way. Again, thanks for your work.

Either way, this PR would have broke the tests, according to the [documentation](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/cheatsheet), AppCenter tests need XUnit package version 2.* in order to run.

**Comment by pulimento** [comment]
P.S. feel free to assign to me the PRs for review. Thanks

**Comment by cmatskas** [comment]
Thanks Jack! That’s greatly appreciated

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by AbhiOnGithub** [comment]
Thanks, I will raise two separate PRs as per suggested way.

**Comment by pulimento** [comment]
That would be awesome, thanks!

**Pull request closed without merging**
